// Démo locale. Renseigner baseUrl et tokenProvider pour brancher le SI du centre.
const ADMIN_API={baseUrl:'',tokenProvider:async()=>null,endpoints:{consultations:'/v1/teleconsultations',messages:'/v1/messages',invoices:'/v1/invoices',metrics:'/v1/metrics'}};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const initials=name=>name.split(' ').filter(Boolean).map(part=>part[0]).slice(-2).join('').toUpperCase();
const storeKey='bmcAdminDemoV2';
const defaultState={
 consultations:[
  {id:'TC-2841',patient:'Mariama Kourouma',phone:'+224 6•• •• 42',reason:'Fièvre & fatigue',doctor:'Dr. A. Barry',time:'15:30',status:'waiting',wait:'08:14',urgent:true,age:'34 ans',notes:'Symptômes depuis 2 jours. Aucun antécédent signalé.'},
  {id:'TC-2842',patient:'Ibrahima Sylla',phone:'+224 6•• •• 18',reason:'Suivi tension',doctor:'Dr. M. Camara',time:'15:35',status:'waiting',wait:'04:52',urgent:false,age:'52 ans',notes:'Suivi mensuel. Dernière mesure déclarée : 14/9.'},
  {id:'TC-2843',patient:'Aïssatou Diallo',phone:'+224 6•• •• 06',reason:'Conseil pédiatrique',doctor:'Dr. B. Diallo',time:'15:40',status:'waiting',wait:'01:27',urgent:false,age:'6 ans',notes:'Consultation avec le parent. Toux depuis hier.'},
  {id:'TC-2839',patient:'Mamadou Bah',phone:'+224 6•• •• 77',reason:'Résultats d’analyse',doctor:'Dr. A. Barry',time:'15:00',status:'active',wait:'12:08',urgent:false,age:'41 ans',notes:'Lecture du bilan sanguin déposé dans le dossier.'},
  {id:'TC-2840',patient:'Fatoumata Camara',phone:'+224 6•• •• 93',reason:'Douleur thoracique',doctor:'Dr. M. Camara',time:'15:15',status:'active',wait:'06:31',urgent:true,age:'47 ans',notes:'Triage effectué. Patiente stable, consignes d’urgence transmises.'},
  {id:'TC-2838',patient:'Oumar Condé',phone:'+224 6•• •• 21',reason:'Renouvellement',doctor:'Dr. A. Barry',time:'14:45',status:'done',wait:'18 min',urgent:false,age:'38 ans',notes:'Compte rendu disponible. Suivi dans 3 mois.'}
 ],
 messages:[
  {name:'Mariama Kourouma',channel:'SMS',text:'Rappel : votre téléconsultation débute aujourd’hui à 15:30.',time:'14:30',status:'Délivré'},
  {name:'Ibrahima Sylla',channel:'SMS',text:'Votre rendez-vous avec le Dr. Camara est confirmé.',time:'13:05',status:'Délivré'},
  {name:'Aïssatou Diallo',channel:'E-mail',text:'Votre document est disponible dans votre espace patient.',time:'11:42',status:'Ouvert'},
  {name:'Mamadou Bah',channel:'SMS',text:'Comment vous sentez-vous après votre consultation ?',time:'Hier',status:'Répondu'}
 ],
 invoices:[
  {id:'FAC-2026-0842',patient:'Mariama Kourouma',service:'Téléconsultation',date:'28 sept.',amount:350000,status:'paid'},
  {id:'FAC-2026-0841',patient:'Ibrahima Sylla',service:'Cardiologie',date:'28 sept.',amount:650000,status:'paid'},
  {id:'FAC-2026-0840',patient:'Fatoumata Camara',service:'Téléconsultation',date:'28 sept.',amount:350000,status:'unpaid'},
  {id:'FAC-2026-0839',patient:'Mamadou Bah',service:'Laboratoire',date:'27 sept.',amount:725000,status:'paid'},
  {id:'FAC-2026-0838',patient:'Oumar Condé',service:'Médecine générale',date:'27 sept.',amount:300000,status:'unpaid'}
 ],
 sent:1284
};
let state=(()=>{try{return Object.assign({},defaultState,JSON.parse(localStorage.getItem(storeKey)||'{}'))}catch{return structuredClone(defaultState)}})();
let activeFilter='all',toastTimer;
const save=()=>localStorage.setItem(storeKey,JSON.stringify(state));
function toast(message){const el=$('#adminToast');$('p',el).textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3200)}
function callApi(path,payload){if(!ADMIN_API.baseUrl)return Promise.resolve({demo:true,payload});return ADMIN_API.tokenProvider().then(token=>fetch(ADMIN_API.baseUrl+path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(payload)}).then(r=>{if(!r.ok)throw Error('api');return r.json()}))}

function openView(name){$$('[data-admin-view]').forEach(b=>b.classList.toggle('active',b.dataset.adminView===name));$$('[data-admin-panel]').forEach(p=>p.classList.toggle('active',p.dataset.adminPanel===name));$('#adminSide').classList.remove('open');$('.menu-admin').setAttribute('aria-expanded','false');scrollTo({top:0,behavior:'smooth'})}
$$('[data-admin-view]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.adminView)));
$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.jump)));
$('.menu-admin').addEventListener('click',event=>{const open=$('#adminSide').classList.toggle('open');event.currentTarget.setAttribute('aria-expanded',String(open))});

const labels={waiting:'En attente',active:'En cours',done:'Terminée'};
function updateCounts(){const count=s=>state.consultations.filter(c=>c.status===s).length;$('#waitingCount').textContent=count('waiting');$('#activeCount').textContent=count('active');$('#doneCount').textContent=18+count('done');$('#overviewWaiting').textContent=count('waiting');$('#waitingBadge').textContent=count('waiting');$('#allCount').textContent=state.consultations.length}
function queueMarkup(c,compact=false){if(compact)return `<div class="queue-item"><span class="avatar">${initials(c.patient)}</span><div><strong>${c.patient}${c.urgent?'<em class="urgency">URGENT</em>':''}</strong><small>${c.reason} · ${c.doctor}</small></div><span class="status ${c.status}">${labels[c.status]}</span><button data-open-consult="${c.id}" aria-label="Ouvrir le dossier">→</button></div>`;return `<tr data-status="${c.status}" data-search="${(c.patient+' '+c.reason+' '+c.doctor).toLowerCase()}"><td><div class="patient-cell"><span class="avatar">${initials(c.patient)}</span><div><strong>${c.patient}${c.urgent?'<em class="urgency">URGENT</em>':''}</strong><small>${c.id} · ${c.phone}</small></div></div></td><td>${c.reason}</td><td>${c.doctor}</td><td><strong>${c.time}</strong><small style="display:block;color:#87958f">${c.status==='waiting'?'Attend '+c.wait:c.wait}</small></td><td><span class="status ${c.status}">${labels[c.status]}</span></td><td><button class="row-action" data-open-consult="${c.id}">Gérer →</button></td></tr>`}
function renderQueues(){const visible=state.consultations.filter(c=>c.status!=='done').slice(0,4);$('#overviewQueue').innerHTML=visible.map(c=>queueMarkup(c,true)).join('');const query=$('#queueSearch').value.trim().toLowerCase();$('#queueTable').innerHTML=state.consultations.filter(c=>(activeFilter==='all'||c.status===activeFilter)&&(!query||(c.patient+' '+c.reason+' '+c.doctor).toLowerCase().includes(query))).map(c=>queueMarkup(c)).join('')||'<tr><td colspan="6" style="text-align:center;padding:35px;color:#71817c">Aucune téléconsultation trouvée.</td></tr>';updateCounts();bindDrawerButtons()}
function bindDrawerButtons(){$$('[data-open-consult]').forEach(b=>b.addEventListener('click',()=>openConsult(b.dataset.openConsult)))}
$$('[data-queue-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-queue-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.queueFilter;renderQueues()}));
$('#queueSearch').addEventListener('input',renderQueues);
function openConsult(id){const c=state.consultations.find(item=>item.id===id);if(!c)return;$('#drawerContent').innerHTML=`<div class="drawer-profile"><i>${initials(c.patient)}</i><h2>${c.patient}</h2><p>${c.id} · ${c.phone}</p><span class="status ${c.status}" style="margin-top:10px">${labels[c.status]}</span></div><div class="drawer-details"><div><small>Créneau</small><strong>Aujourd’hui · ${c.time}</strong></div><div><small>Praticien</small><strong>${c.doctor}</strong></div><div><small>Âge</small><strong>${c.age}</strong></div><div><small>Mode</small><strong>Vidéo sécurisée</strong></div></div><div class="drawer-section"><h3>Motif de consultation</h3><p><strong>${c.reason}</strong></p><p>${c.notes}</p></div><div class="drawer-section"><h3>État technique</h3><p>✓ Connexion stable &nbsp; ✓ Caméra testée &nbsp; ✓ Consentement recueilli</p></div><div class="drawer-actions">${c.status==='waiting'?`<button class="secondary" data-drawer-sms>Envoyer un SMS</button><button class="primary" data-action-consult="start">Ouvrir la salle</button>`:c.status==='active'?`<button class="secondary" data-drawer-sms>Envoyer un SMS</button><button class="primary" data-action-consult="finish">Terminer</button>`:`<button class="secondary" data-drawer-sms>Envoyer le compte rendu</button><button class="primary" data-action-consult="reopen">Rouvrir</button>`}</div>`;$('#consultDrawer').dataset.id=id;$('#drawerBackdrop').hidden=false;$('#consultDrawer').classList.add('open');$('#consultDrawer').setAttribute('aria-hidden','false');$('[data-drawer-sms]')?.addEventListener('click',()=>{closeDrawer();openSms('followup',c.patient)});const actionButton=$('[data-action-consult]');actionButton?.addEventListener('click',()=>advanceConsult(id,actionButton.dataset.actionConsult))}
function closeDrawer(){$('#consultDrawer').classList.remove('open');$('#consultDrawer').setAttribute('aria-hidden','true');setTimeout(()=>$('#drawerBackdrop').hidden=true,300)}
$('.drawer-close').addEventListener('click',closeDrawer);$('#drawerBackdrop').addEventListener('click',closeDrawer);
async function advanceConsult(id,action){const c=state.consultations.find(item=>item.id===id);if(!c)return;const next={start:'active',finish:'done',reopen:'waiting'}[action];await callApi(ADMIN_API.endpoints.consultations+'/'+id,{status:next});c.status=next;c.wait=next==='active'?'00:00':c.wait;save();renderQueues();closeDrawer();toast(action==='start'?'Salle ouverte — le praticien peut rejoindre':action==='finish'?'Téléconsultation terminée et archivée':'Dossier replacé dans la file')}
$('#addUrgent').addEventListener('click',()=>{const next=2844+state.consultations.filter(c=>c.id.startsWith('TC-28')).length;state.consultations.unshift({id:'TC-'+next,patient:'Patient urgence',phone:'+224 6•• •• ••',reason:'Évaluation urgente',doctor:'Médecin de garde',time:new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),status:'waiting',wait:'00:00',urgent:true,age:'À confirmer',notes:'Ajout manuel depuis le centre de contrôle.'});save();renderQueues();toast('Urgence ajoutée en tête de file')});

const templates={reminder:'Bonjour [Prénom], rappel de votre rendez-vous Best Medical Center demain à [Heure]. Répondez OUI pour confirmer.',followup:'Bonjour [Prénom], comment vous sentez-vous depuis votre consultation ? Notre équipe reste disponible si besoin.',results:'Bonjour [Prénom], vos résultats sont disponibles dans votre espace patient sécurisé Best Medical Center.',payment:'Bonjour [Prénom], votre facture Best Medical Center reste en attente. Vous pouvez la régler depuis votre espace patient.'};
function openSms(template='custom',patient='Mariama Kourouma'){const modal=$('#smsModal');modal.hidden=false;$('#smsPatient').value=patient;$('#smsTemplate').value=template;$('#smsText').value=templates[template]||'';updateSmsPreview();setTimeout(()=>$('#smsText').focus(),100)}
function closeSms(){$('#smsModal').hidden=true}
$$('[data-compose]').forEach(b=>b.addEventListener('click',()=>openSms()));$$('[data-template]').forEach(b=>b.addEventListener('click',()=>openSms(b.dataset.template)));
$$('#smsModal .modal-close, #smsModal .modal-backdrop').forEach(b=>b.addEventListener('click',closeSms));
$('#smsTemplate').addEventListener('change',event=>{$('#smsText').value=templates[event.target.value]||'';updateSmsPreview()});
$('#smsRecipients').addEventListener('change',event=>$('#patientField').hidden=event.target.value!=='patient');
function updateSmsPreview(){const text=$('#smsText').value;$('#smsChars').textContent=text.length;$('#smsParts').textContent=(Math.max(1,Math.ceil(text.length/160)))+' SMS';$('#smsPreview').textContent=text||'Votre message apparaîtra ici.'}
$('#smsText').addEventListener('input',updateSmsPreview);
$('#smsForm').addEventListener('submit',async event=>{event.preventDefault();const recipients=$('#smsRecipients'),count={patient:1,tomorrow:18,video:24,unpaid:7}[recipients.value];const patient=recipients.value==='patient'?$('#smsPatient').value:recipients.options[recipients.selectedIndex].text;const payload={recipients:recipients.value,patient,text:$('#smsText').value};const button=$('#smsForm button[type="submit"]');button.disabled=true;button.textContent='Envoi…';try{await callApi(ADMIN_API.endpoints.messages,payload);state.sent+=count;state.messages.unshift({name:patient,channel:'SMS',text:payload.text,time:'À l’instant',status:'Délivré'});save();renderMessages();closeSms();toast(`${count} SMS ${count>1?'envoyés':'envoyé'} avec succès`)}catch{toast('Échec de l’envoi — vérifiez le connecteur API')}finally{button.disabled=false;button.textContent='Envoyer le SMS →'}});
function renderMessages(){$('#sentTotal').textContent=state.sent.toLocaleString('fr-FR');$('#messageLog').innerHTML=state.messages.slice(0,8).map(m=>`<div class="message-entry"><i>${m.channel==='SMS'?'✉':'@'}</i><div><strong>${m.name}</strong><small>${m.channel} · ${m.status}</small><p>${m.text}</p></div><time>${m.time}</time></div>`).join('')}

$$('.rule input').forEach(input=>input.addEventListener('change',()=>toast(input.checked?'Scénario automatique activé':'Scénario mis en pause')));
$('#runReminders').addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;button.textContent='Exécution…';await new Promise(r=>setTimeout(r,900));state.sent+=16;save();renderMessages();button.disabled=false;button.textContent='✓ Rappels envoyés';toast('16 rappels envoyés · 2 dossiers à vérifier');setTimeout(()=>button.textContent='▶ Lancer les rappels',2400)});

const money=value=>value.toLocaleString('fr-FR')+' GNF';
function renderInvoices(){$('#invoiceTable').innerHTML=state.invoices.map(i=>`<tr data-invoice="${i.id}" ${i.status==='unpaid'?'title="Cliquer pour marquer comme réglée" style="cursor:pointer"':''}><td><strong>${i.id}</strong></td><td>${i.patient}</td><td>${i.service}</td><td>${i.date}</td><td><strong>${money(i.amount)}</strong></td><td><span class="status ${i.status}">${i.status==='paid'?'Réglée':'À relancer'}</span></td></tr>`).join('');$$('[data-invoice]').forEach(row=>row.addEventListener('click',()=>{const invoice=state.invoices.find(i=>i.id===row.dataset.invoice);if(invoice.status==='paid')return;invoice.status='paid';save();renderInvoices();toast(`${invoice.id} marquée comme réglée`)}))}
$('#exportAccounting').addEventListener('click',()=>{const csv=['Facture,Patient,Service,Date,Montant,Statut',...state.invoices.map(i=>[i.id,i.patient,i.service,i.date,i.amount,i.status].join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='comptabilite-bmc-demo.csv';a.click();URL.revokeObjectURL(a.href);toast('Rapport CSV généré')});

const ranges={7:{satisfaction:92,wait:'09:12',show:'89,4%',video:'97,6%'},30:{satisfaction:94,wait:'08:24',show:'91,8%',video:'98,2%'},90:{satisfaction:93,wait:'08:51',show:'90,6%',video:'97,9%'}};
$$('[data-range]').forEach(button=>button.addEventListener('click',()=>{$$('[data-range]').forEach(b=>b.classList.remove('active'));button.classList.add('active');const data=ranges[button.dataset.range];$('#satisfactionScore').textContent=data.satisfaction;$('#waitScore').textContent=data.wait;$('#showScore').textContent=data.show;$('#videoScore').textContent=data.video;toast(`Indicateurs actualisés sur ${button.textContent}`)}));
$('.global-search input').addEventListener('keydown',event=>{if(event.key!=='Enter')return;openView('teleconsult');$('#queueSearch').value=event.currentTarget.value;renderQueues()});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeDrawer();closeSms()}});

renderQueues();renderMessages();renderInvoices();
