const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const toast=message=>{const el=$('.toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)};

// Navigation et animation progressive, sans bibliothèque externe.
const header=$('.site-header');if(header)addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>25),{passive:true});
const menu=$('.menu-toggle'),mobile=$('.mobile-menu');if(menu&&mobile)menu.addEventListener('click',()=>{const open=mobile.classList.toggle('open');menu.setAttribute('aria-expanded',open)});
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.1});$$('.reveal').forEach(el=>observer.observe(el))}else $$('.reveal').forEach(el=>el.classList.add('visible'));
$$('[data-toast]').forEach(button=>button.addEventListener('click',()=>toast(button.dataset.toast)));
if(!document.body.classList.contains('tele-page')){const signal=document.createElement('a');signal.className='tele-signal';signal.href='teleconsultation.html';signal.setAttribute('aria-label','Médecin en ligne — ouvrir la téléconsultation');signal.innerHTML='<i>⌁</i><span><strong>Médecin en ligne</strong><small>Voir les créneaux</small></span><b>→</b>';document.body.append(signal)}

// Sélecteur de service et créneaux.
const drawer=$('.service-drawer');
if(drawer){$$('[data-service]').forEach(button=>button.addEventListener('click',()=>{$('.drawer-service').textContent=button.dataset.service;drawer.hidden=false;document.body.classList.add('modal-open')}));$$('[data-drawer-close]').forEach(button=>button.addEventListener('click',()=>{drawer.hidden=true;document.body.classList.remove('modal-open')}));$$('.slot-days button').forEach(button=>button.addEventListener('click',()=>{$$('.slot-days button').forEach(b=>b.classList.remove('active'));button.classList.add('active')}));$$('.slot-times button').forEach(button=>button.addEventListener('click',()=>{$$('.slot-times button').forEach(b=>b.classList.remove('active'));button.classList.add('active');$('.drawer-confirm').disabled=false}));$('.drawer-confirm').addEventListener('click',()=>{toast('Rendez-vous de démonstration confirmé');drawer.hidden=true;document.body.classList.remove('modal-open')})}

// Fiche détaillée de chaque service.
const serviceCatalog={
 general:{title:'Médecine générale',category:'Médecine & prévention',symbol:'✚',intro:'Une prise en charge globale pour comprendre vos symptômes, prévenir les risques et organiser votre suivi.',duration:'30 minutes',mode:'Au centre ou en vidéo',professional:'Médecin généraliste',image:'equipe-soins.jpg',indicationsTitle:'Pour vos besoins de santé du quotidien.',indications:['Fièvre, douleur ou fatigue persistante','Suivi de tension, diabète ou traitement','Bilan de santé et prévention','Orientation vers un spécialiste'],included:['Entretien médical et antécédents','Examen clinique adapté au motif','Explication des hypothèses et options','Prescription ou examens si nécessaire','Plan de suivi dans votre espace patient'],during:'Échange, examen clinique et décision partagée.',prep:['Pièce d’identification','Ordonnances et traitements en cours','Résultats d’examens récents','Liste de vos questions'],faq:'Oui, une consultation de médecine générale peut être réservée directement.'},
 femme:{title:'Santé de la femme',category:'Prévention & accompagnement',symbol:'♡',intro:'Un accompagnement confidentiel et attentif à chaque étape de la vie.',duration:'30 à 45 minutes',mode:'Au centre · vidéo selon le motif',professional:'Médecin ou sage-femme',image:'accompagnement-patiente.jpg',indicationsTitle:'Pour un suivi régulier ou une question ponctuelle.',indications:['Consultation gynécologique et prévention','Suivi de grossesse et postnatal','Contraception et planification familiale','Douleurs ou symptômes inhabituels'],included:['Écoute du motif et des priorités','Examen adapté avec votre accord','Information sur le dépistage','Prescription d’analyses si utile','Organisation du prochain suivi'],during:'Échange confidentiel, examen consenti et recommandations personnalisées.',prep:['Carnet ou documents de suivi','Date des dernières règles si pertinente','Résultats d’analyses ou d’imagerie','Traitements et allergies connus'],faq:'Oui, un premier rendez-vous peut être pris sans ordonnance.'},
 cardiologie:{title:'Cardiologie',category:'Cœur & circulation',symbol:'◉',intro:'Une évaluation structurée du risque cardiovasculaire et un suivi compréhensible.',duration:'45 minutes',mode:'Au centre principalement',professional:'Médecin cardiologue',image:'direction.jpg',indicationsTitle:'Pour prévenir, évaluer ou suivre un problème cardiaque.',indications:['Hypertension ou palpitations','Douleur thoracique non urgente','Essoufflement à l’effort','Suivi cardiovasculaire régulier'],included:['Entretien sur les facteurs de risque','Mesure de tension et examen clinique','ECG selon indication','Lecture des examens disponibles','Programme de suivi personnalisé'],during:'Bilan clinique, examens utiles et explication claire des résultats.',prep:['Ordonnance ou lettre du médecin','Liste des traitements','Anciens ECG et comptes rendus','Relevés de tension à domicile'],faq:'Une orientation médicale est recommandée, mais le centre peut vous guider.'},
 infirmiers:{title:'Soins infirmiers',category:'Soins & accompagnement',symbol:'⌁',intro:'Des soins techniques réalisés avec attention, explications et continuité.',duration:'15 à 40 minutes',mode:'Au centre',professional:'Infirmier ou infirmière',image:'accueil-soignante.jpg',indicationsTitle:'Pour réaliser un soin prescrit ou assurer un suivi.',indications:['Pansement simple ou complexe','Injection et perfusion prescrite','Surveillance de constantes','Accompagnement post-opératoire'],included:['Vérification de la prescription','Évaluation avant le soin','Réalisation selon le protocole','Conseils de surveillance','Traçabilité dans le dossier'],during:'Vérification, réalisation du soin et conseils pour le retour à domicile.',prep:['Ordonnance médicale si requise','Matériel ou produit prescrit','Compte rendu opératoire si utile','Informations sur vos allergies'],faq:'Certains soins nécessitent une ordonnance. L’accueil vous le confirmera.'},
 imagerie:{title:'Imagerie & examens',category:'Diagnostic & exploration',symbol:'✦',intro:'Un parcours guidé depuis la prescription jusqu’à la remise du compte rendu.',duration:'20 à 60 minutes',mode:'Au centre',professional:'Équipe d’imagerie',image:'analyse-medicale.jpg',indicationsTitle:'Pour explorer une situation ou suivre son évolution.',indications:['Échographie prescrite','Examen fonctionnel','Contrôle après traitement','Exploration demandée par un médecin'],included:['Vérification de l’indication','Préparation et explication','Réalisation de l’examen','Lecture par le professionnel','Compte rendu numérique sécurisé'],during:'Préparation, examen et information sur le délai de résultat.',prep:['Ordonnance de l’examen','Anciens examens comparables','Consignes de préparation reçues','Pièce d’identification'],faq:'La plupart des examens nécessitent une prescription médicale.'},
 urgent:{title:'Consultation urgente',category:'Orientation rapide',symbol:'⚡',intro:'Un premier échange pour évaluer votre situation et vous orienter sans délai inutile.',duration:'15 à 30 minutes',mode:'Brief en ligne ou au centre',professional:'Équipe de première orientation',image:'poste-accueil.jpg',indicationsTitle:'Pour un problème récent qui demande un avis rapide.',indications:['Fièvre ou douleur récente','Symptômes digestifs ou cutanés','Aggravation sans danger immédiat','Besoin d’une orientation rapide'],included:['Brief initial des symptômes','Évaluation du niveau de priorité','Premier avis médical','Orientation vers le bon service','Consignes de surveillance'],during:'Évaluation rapide, premières consignes et orientation adaptée.',prep:['Heure de début des symptômes','Température ou mesures disponibles','Traitements déjà pris','Antécédents importants'],faq:'Oui, mais en cas de danger immédiat contactez le service d’urgence local.'}
};
const detailRoot=$('.service-detail-page');if(detailRoot){const key=new URLSearchParams(location.search).get('service')||'general',service=serviceCatalog[key]||serviceCatalog.general;document.title=`${service.title} — Best Medical Center`;$('.detail-title').textContent=service.title;$('.detail-category').textContent=service.category;$('.service-symbol').textContent=service.symbol;$('.detail-intro').textContent=service.intro;$('.detail-duration').textContent=service.duration;$('.detail-mode').textContent=service.mode;$('.detail-professional').textContent=service.professional;$('.indications-title').textContent=service.indicationsTitle;$('.detail-image').src=service.image;$('.journey-during').textContent=service.during;$('.faq-one').textContent=service.faq;$('.detail-cta-title').textContent=`Prenez rendez-vous en ${service.title.toLowerCase()}.`;$('.indications-grid').innerHTML=service.indications.map((item,i)=>`<article><span>0${i+1}</span><strong>${item}</strong></article>`).join('');$('.included-list').innerHTML=service.included.map((item,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><span>${item}</span><i>✓</i></div>`).join('');$('.preparation-list').innerHTML=service.prep.map(item=>`<li><i>✓</i>${item}</li>`).join('');$$('.detail-book').forEach(button=>button.addEventListener('click',()=>{$('.drawer-service').textContent=service.title;drawer.hidden=false;document.body.classList.add('modal-open')}))}

// Bibliothèque de conseils et lecture d’articles.
const adviceArticles={
 prevention:{category:'Prévention',title:'Le bilan de santé : quand et pourquoi le faire ?',lede:'Un bilan aide à faire le point sur les facteurs de risque avant l’apparition de symptômes.',body:['La fréquence d’un bilan dépend de l’âge, des antécédents et du contexte personnel. Il ne s’agit pas d’accumuler les examens, mais de choisir ceux qui répondent à un besoin réel.','Préparez la consultation avec vos traitements, antécédents familiaux et questions. Le professionnel pourra proposer des mesures simples, un examen clinique ou certains dépistages.'],takeaway:'La prévention se construit avec un professionnel, selon votre situation individuelle.'},
 tension:{category:'Prévention',title:'Bien mesurer sa tension à la maison',lede:'Une mesure bien réalisée est plus utile qu’une succession de chiffres pris au hasard.',body:['Installez-vous au calme pendant quelques minutes, assis, le dos soutenu et les pieds au sol. Placez le brassard sur un bras découvert, à hauteur du cœur.','Évitez café, tabac et exercice juste avant la mesure. Notez les résultats et les horaires sans modifier seul votre traitement.'],takeaway:'Une valeur isolée ne suffit pas pour conclure. Partagez une série de mesures avec votre médecin.'},
 hydratation:{category:'Nutrition',title:'Hydratation : les signes à surveiller',lede:'Les besoins augmentent avec la chaleur, l’activité physique, la fièvre et certains âges de la vie.',body:['Buvez régulièrement sans attendre une soif intense. Une bouche sèche, des urines foncées, des étourdissements ou une fatigue inhabituelle peuvent signaler un manque d’eau.','Les jeunes enfants, personnes âgées et personnes malades nécessitent une vigilance particulière. Certaines maladies imposent toutefois de limiter les apports.'],takeaway:'Adaptez l’hydratation à votre situation et demandez conseil en cas de maladie chronique.'},
 fievre:{category:'Famille',title:'Fièvre chez l’enfant : les premiers réflexes',lede:'La température compte, mais l’état général de l’enfant est tout aussi important.',body:['Proposez régulièrement à boire, ne couvrez pas excessivement l’enfant et observez son comportement, sa respiration et sa capacité à s’alimenter.','L’âge, la durée de la fièvre et les signes associés orientent la conduite à tenir. Chez un très jeune nourrisson ou en présence de signes inquiétants, demandez rapidement un avis médical.'],takeaway:'En cas de difficulté respiratoire, somnolence inhabituelle ou convulsion, sollicitez immédiatement une aide urgente.'},
 sommeil:{category:'Bien-être',title:'Retrouver un sommeil plus régulier',lede:'Des horaires stables et une transition calme aident le corps à retrouver son rythme.',body:['Levez-vous à une heure régulière, exposez-vous à la lumière le matin et réduisez les écrans avant le coucher. Une activité physique en journée peut également améliorer le sommeil.','Si les troubles durent, s’accompagnent de ronflements importants ou affectent fortement la journée, parlez-en à un professionnel.'],takeaway:'Cherchez la régularité plutôt que la perfection et observez les progrès sur plusieurs semaines.'},
 depistage:{category:'Prévention',title:'Dépistage : ne pas attendre les symptômes',lede:'Certains problèmes de santé évoluent silencieusement et peuvent être repérés plus tôt.',body:['Le dépistage pertinent dépend de l’âge, du sexe, des antécédents et des expositions. Il doit être discuté pour comprendre ses bénéfices et ses limites.','Un résultat de dépistage n’est pas toujours un diagnostic : des examens complémentaires peuvent être nécessaires.'],takeaway:'Demandez quels dépistages sont réellement recommandés dans votre situation.'},
 glycemie:{category:'Nutrition',title:'Comprendre sa glycémie',lede:'La glycémie mesure la quantité de glucose présente dans le sang à un moment donné.',body:['Le résultat dépend notamment du jeûne, du repas précédent, de l’activité et de certains médicaments. Respectez les consignes données avant le prélèvement.','Une valeur inhabituelle doit être interprétée dans son contexte et parfois contrôlée. Ne modifiez pas votre alimentation ou votre traitement sur un chiffre isolé.'],takeaway:'Conservez vos résultats et faites-les interpréter par le professionnel qui suit votre santé.'}
};
$$('[data-advice-filter]').forEach(button=>button.addEventListener('click',()=>{$$('[data-advice-filter]').forEach(b=>b.classList.remove('active'));button.classList.add('active');$$('.advice-grid>article').forEach(card=>card.hidden=button.dataset.adviceFilter!=='all'&&card.dataset.category!==button.dataset.adviceFilter)}));
const adviceSearch=$('.advice-search input');if(adviceSearch)adviceSearch.addEventListener('input',()=>{let count=0;$$('.advice-grid>article').forEach(card=>{const match=card.textContent.toLowerCase().includes(adviceSearch.value.toLowerCase());card.hidden=!match;if(match)count++});$('.advice-empty').hidden=count>0});
const adviceModal=$('.advice-modal');$$('[data-article]').forEach(card=>card.addEventListener('click',event=>{if(event.target.closest('button')||card.classList.contains('featured-advice')){const article=adviceArticles[card.dataset.article];if(!article||!adviceModal)return;$('.article-category').textContent=article.category;$('.article-title').textContent=article.title;$('.article-lede').textContent=article.lede;$('.article-body').innerHTML=article.body.map(p=>`<p>${p}</p>`).join('');$('.article-takeaway').textContent=article.takeaway;adviceModal.hidden=false;document.body.classList.add('modal-open')}}));$$('[data-advice-close]').forEach(button=>button.addEventListener('click',()=>{adviceModal.hidden=true;document.body.classList.remove('modal-open')}));

// Recherche et réservation laboratoire.
const labSearch=$('.lab-search input');if(labSearch)labSearch.addEventListener('input',()=>{let visible=0;$$('.lab-row[data-lab]').forEach(row=>{const show=row.dataset.lab.toLowerCase().includes(labSearch.value.toLowerCase());row.hidden=!show;if(show)visible++});$('.lab-empty').hidden=visible>0});
$$('[data-lab] button,[data-lab-book]').forEach(button=>button.addEventListener('click',()=>toast('Créneau de prélèvement ajouté à la sélection')));

// Annuaire et parcours des médecins.
$$('[data-filter]').forEach(button=>button.addEventListener('click',()=>{$$('[data-filter]').forEach(b=>b.classList.remove('active'));button.classList.add('active');$$('.doctor-card').forEach(card=>card.hidden=button.dataset.filter!=='all'&&card.dataset.specialty!==button.dataset.filter)}));
const profileModal=$('.profile-modal');$$('[data-doctor]').forEach(button=>button.addEventListener('click',()=>{if(!profileModal)return;$('.profile-modal h2').textContent=button.dataset.doctor;$('.profile-path').textContent=button.dataset.path;$('.profile-avatar').textContent=button.dataset.doctor.split(' ').slice(-1)[0].slice(0,2).toUpperCase();profileModal.hidden=false;document.body.classList.add('modal-open')}));$$('[data-profile-close]').forEach(button=>button.addEventListener('click',()=>{profileModal.hidden=true;document.body.classList.remove('modal-open')}));

// Simulateur d’assurance.
const coverage=$('#coverageForm');if(coverage)coverage.addEventListener('submit',event=>{event.preventDefault();$('.coverage-result').hidden=false;toast('Simulation terminée — résultat indicatif')});

// Tableau de bord patient.
function openPatientView(name){$$('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===name));$$('[data-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.panel===name));scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(button=>button.addEventListener('click',()=>openPatientView(button.dataset.view)));$$('[data-view-jump]').forEach(button=>button.addEventListener('click',()=>openPatientView(button.dataset.viewJump)));
$$('[data-doc]').forEach(card=>card.addEventListener('click',()=>{$$('[data-doc]').forEach(c=>c.classList.remove('selected'));card.classList.add('selected');const title=$('strong',card).textContent;$('.preview-toolbar>span').textContent=title.replaceAll(' ','_')+'.pdf';$('.paper h2').textContent=title;toast('Aperçu du document chargé')}));
const messageForm=$('.conversation form');if(messageForm)messageForm.addEventListener('submit',event=>{event.preventDefault();const input=$('input',messageForm);if(!input.value.trim())return;const message=document.createElement('p');message.className='sent';message.innerHTML=`${input.value.replace(/[<>]/g,'')}<small>À l’instant</small>`;$('.messages').append(message);input.value='';toast('Message ajouté à la conversation de démonstration')});
const savedAppointment=JSON.parse(localStorage.getItem('bmcAppointment')||'null');if(savedAppointment&&document.body.classList.contains('patient-page')){const overviewDetails=$$('.next-card .appt-details strong');if(overviewDetails[0])overviewDetails[0].textContent=savedAppointment.label;if(overviewDetails[1])overviewDetails[1].textContent=`${savedAppointment.time} · 30 min`;const upcoming=$('.appointment-timeline .upcoming');if(upcoming){const date=new Date(savedAppointment.date+'T12:00:00');$('small',upcoming).textContent=date.toLocaleDateString('fr-FR',{month:'short'}).replace('.','').toUpperCase();$('strong',upcoming).textContent=String(date.getDate()).padStart(2,'0');$('.date-block span',upcoming).textContent=savedAppointment.time}}

// Téléconsultation: couche prête à brancher à un endpoint de création de salle.
const VIDEO_API={baseUrl:'',createRoomEndpoint:'/v1/teleconsultations',tokenProvider:async()=>null};
let consultationContext={mode:'scheduled',symptom:'Consultation programmée'},mediaStream=null,clock=null,elapsed=0;
const teleIntro=$('.tele-intro'),teleFlow=$('.tele-flow');
function showFlow(name,step=1){if(!teleFlow)return;teleIntro.hidden=true;teleFlow.hidden=false;$$('[data-flow]').forEach(el=>el.hidden=el.dataset.flow!==name);$$('.flow-progress span').forEach((el,i)=>el.classList.toggle('active',i<step));$('.flow-progress small b').textContent=step}
$$('[data-care-mode]').forEach(button=>button.addEventListener('click',()=>{consultationContext.mode=button.dataset.careMode;showFlow(button.dataset.careMode,1)}));
if(teleFlow){const mode=new URLSearchParams(location.search).get('mode');if(mode==='urgent'||mode==='scheduled'){consultationContext.mode=mode;showFlow(mode,1)}}
const flowBack=$('[data-flow-back]');if(flowBack)flowBack.addEventListener('click',()=>{teleFlow.hidden=true;teleIntro.hidden=false;$$('[data-flow]').forEach(el=>el.hidden=true)});
let calendarOffset=0,selectedAppointmentDate=null,selectedAppointmentTime='';
const availableByDay={0:[],1:['09:00','10:30','14:00','16:30'],2:['08:30','11:00','15:30'],3:['09:30','12:00','14:30','17:00'],4:['10:00','11:30','16:00'],5:['08:30','10:30','13:30'],6:['09:00','11:00']};
function formatAppointmentDate(date){return date.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
function renderCalendar(){const container=$('.calendar-days');if(!container)return;container.innerHTML='';const start=new Date();start.setHours(12,0,0,0);start.setDate(start.getDate()+calendarOffset*7);$('.calendar-month').textContent=start.toLocaleDateString('fr-FR',{month:'long',year:'numeric'}).replace(/^./,c=>c.toUpperCase());for(let i=0;i<7;i++){const date=new Date(start);date.setDate(start.getDate()+i);const slots=availableByDay[date.getDay()]||[];const button=document.createElement('button');button.className=`calendar-day ${slots.length?(slots.length<4?'limited':'available'):'unavailable'}`;button.disabled=!slots.length;button.innerHTML=`<small>${date.toLocaleDateString('fr-FR',{weekday:'short'}).replace('.','')}</small><strong>${date.getDate()}</strong><span>${slots.length?slots.length+' créneaux':'Complet'}</span>`;button.addEventListener('click',()=>selectCalendarDate(date,slots,button));container.append(button)}}
function selectCalendarDate(date,slots,button){selectedAppointmentDate=date;selectedAppointmentTime='';$$('.calendar-day').forEach(b=>b.classList.remove('selected'));button.classList.add('selected');const label=formatAppointmentDate(date);$('.selected-date-label').textContent=label;$('.recap-date').textContent=label;$('.recap-time').textContent='—';$('.confirm-booking').disabled=true;const slotsContainer=$('.available-slots');slotsContainer.innerHTML='';slots.forEach(time=>{const slot=document.createElement('button');slot.textContent=time;slot.addEventListener('click',()=>{$$('.available-slots button').forEach(b=>b.classList.remove('selected'));slot.classList.add('selected');selectedAppointmentTime=time;$('.recap-time').textContent=time;$('.confirm-booking').disabled=false});slotsContainer.append(slot)})}
if($('.calendar-days')){renderCalendar();$('[data-calendar-prev]').addEventListener('click',()=>{calendarOffset=Math.max(0,calendarOffset-1);renderCalendar()});$('[data-calendar-next]').addEventListener('click',()=>{calendarOffset++;renderCalendar()});$('.confirm-booking').addEventListener('click',()=>{if(!selectedAppointmentDate||!selectedAppointmentTime)return;const appointment={date:selectedAppointmentDate.toISOString().slice(0,10),label:formatAppointmentDate(selectedAppointmentDate),time:selectedAppointmentTime,doctor:'Dr. A. Barry',type:'Téléconsultation'};localStorage.setItem('bmcAppointment',JSON.stringify(appointment));$('.ticket-date').textContent=appointment.label;$('.ticket-time').textContent=appointment.time;updateAppointmentCountdown(appointment);showFlow('booking-confirmed',3)})}
function updateAppointmentCountdown(appointment){const target=new Date(`${appointment.date}T${appointment.time}:00`),diff=Math.max(0,target-Date.now()),days=Math.floor(diff/86400000),hours=Math.floor(diff%86400000/3600000);$('.appointment-countdown').textContent=diff?`${days} j · ${hours} h`:'Salle disponible'}
const simulateDay=$('[data-simulate-day]');if(simulateDay)simulateDay.addEventListener('click',()=>showFlow('preflight',3));
const triage=$('#triageForm');if(triage)triage.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(triage);consultationContext.symptom=data.get('symptom')||'Autre';$('.summary-symptom').textContent=consultationContext.symptom;$('.room-symptom').textContent=`${consultationContext.symptom} · ${data.get('duration')}`;showFlow('result',2)});
$$('[data-start-preflight]').forEach(button=>button.addEventListener('click',()=>showFlow('preflight',2)));
const cameraButton=$('.preflight-page [data-device="camera"]');if(cameraButton)cameraButton.addEventListener('click',async()=>{if(mediaStream){mediaStream.getTracks().forEach(track=>track.stop());mediaStream=null;$('.video-preview video').srcObject=null;$('.camera-placeholder').style.display='grid';cameraButton.classList.remove('active');return}try{mediaStream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});$('.video-preview video').srcObject=mediaStream;$('.camera-placeholder').style.display='none';cameraButton.classList.add('active');toast('Caméra activée localement')}catch{toast('Caméra indisponible — vous pouvez continuer sans vidéo')}});
const micButton=$('.preflight-page [data-device="mic"]');if(micButton)micButton.addEventListener('click',()=>{micButton.classList.toggle('active');toast(micButton.classList.contains('active')?'Micro activé':'Micro coupé')});
async function createRemoteRoom(){if(!VIDEO_API.baseUrl)return {id:'demo-room',mode:'demo'};const token=await VIDEO_API.tokenProvider();const response=await fetch(`${VIDEO_API.baseUrl}${VIDEO_API.createRoomEndpoint}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(consultationContext)});if(!response.ok)throw new Error('room_creation_failed');return response.json()}
const enterRoom=$('[data-enter-room]');if(enterRoom)enterRoom.addEventListener('click',async()=>{enterRoom.disabled=true;enterRoom.textContent='Connexion…';try{await createRemoteRoom();showFlow('room',3);elapsed=0;clock=setInterval(()=>{elapsed++;$('.call-duration').textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`},1000)}catch{toast('Connexion impossible. Réessayez.')}finally{enterRoom.disabled=false;enterRoom.textContent='Entrer dans la salle →'}});
$$('[data-room-device]').forEach(button=>button.addEventListener('click',()=>button.classList.toggle('active')));const endConsult=$('.end-consult');if(endConsult)endConsult.addEventListener('click',()=>{clearInterval(clock);if(mediaStream)mediaStream.getTracks().forEach(track=>track.stop());showFlow('ended',3)});
